Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -43,5 +43,6 @@ jobs:
       env:
         NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
       run: |
-        echo $NEXUS_PASSWORD | docker login ${{ env.DOCKER_REGISTRY }} -u admin --password-stdin
-        docker push ${{ env.DOCKER_REGISTRY }}/repository/test/${{ env.DOCKER_IMAGE }}:latest
+        echo $NEXUS_PASSWORD | docker login ${{ env.DOCKER_REGISTRY }} -u admin --password-stdin || { echo "Docker login failed"; exit 1; }
+        docker push ${{ env.DOCKER_REGISTRY }}/repository/test/${{ env.DOCKER_IMAGE }}:latest || { echo "Docker push failed"; exit 1; }
+
